### ISSUE TITLE
[CKEditor5] superscript gets casted to subscript

### ISSUE THREAD

**Issue by ErikDohmen** [wiris/html-integrations#1001]
## Description

We add a superscript formula in the editor through the plugin and then it gets shown correctly, but once we reload the code (or do a setData) it gets converted to a subscript formula

## Environment

wiris/mathtype-ckeditor5: 8.10.0

_What is the relevant software and their versions?_

- ckeditor/ckeditor5-core: 42.0.0

## Steps to reproduce

1. Create a formula with a left-superscript formula
2. insert the formula into the editor
3. as per your own website https://demo.wiris.com/integrations/ckeditor/ copy the generated html
4. insert the data back into the editor through the console in my case editor.setData('<p><math xmlns="http://www.w3.org/1998/Math/MathML"><mmultiscripts><mi>b</mi><mprescripts> </mprescripts><none> </none><mi>a</mi></mmultiscripts><mo> </mo><mo>=</mo><mo> </mo><mi>a</mi><mi>b</mi><mi>c</mi></math></p>');
5. see that in the editor you get an a with a left subscript instead of a left superscript

## Expected result

the same as generated at first a left superscript

## Actual result

a left subscript

## Other details

Both in our environment as well as on the demo on your site

**Comment by usantos-at-wiris** [comment]
Hi @ErikDohmen, thanks for reaching us! 

We are currently working on this, well be ready for the next release!
