### ISSUE TITLE
`<mfenced>` tag is deprecated

### ISSUE THREAD

**Issue by DrAliRagab** [wiris/html-integrations#1002]
mathType outputs `<mfenced>` tag which is deprecated and is not supported any more and is not rendered on any modern browser.

 see: [\<mfenced\>](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced)

**Comment by DrAliRagab** [comment]
polyfill: [mathml-polyfills/mfenced](https://github.com/w3c/mathml-polyfills/tree/main/mfenced)

**Comment by carla-at-wiris** [comment]
Hello, thank you for writing us!

[The MDN article on mfenced](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced) states that the `mfenced` element is "deprecated". You may be wondering why we output "deprecated" MathML. This must be put into perspective: `mfenced` is "deprecated" inside web pages, i.e. when it's used as an HTML element.

The `mfenced` attribute can be found in the [MathML 4 spec](https://www.w3.org/TR/mathml4/#presm_mfenced) (currently a Working Draft) in [section 3.3.8](https://www.w3.org/TR/mathml4/#presm_mfenced). However, it's missing from the [MathML Core](https://w3c.github.io/mathml-core/) spec (and also tagged as not-core in MathML 4), which is a subset of MathML intended to be implemented by web browsers.

MathType Web uses the "**full**" version of MathML (MathML 3, MathML 4) and not MathML Core, therefore these deprecation warnings don't apply. MathType Web only uses MathML as an interchange format for mathematical equations, it's never inserted into the actual page.

To make it short: we're not affected by this "deprecation" warning. We're using MathML, not MathML Core, which is the one missing the `mfenced` element among other ones.
