### ISSUE TITLE
[CKEditor5] Tracking error in console

### ISSUE THREAD

**Issue by usqr** [wiris/html-integrations#1010]
## Description

_What does the bug consist in?_

## Environment

_Which version of MathType does this happen in?_

_What is the relevant software and their versions?_

- CKEditor 43.1.1
- no framework
- Brave - Wersja 1.70.119 Chromium: 129.0.6668.70 (Oficjalna wersja) (arm64)
- MacOS Sonoma 14.6.1

## Steps to reproduce

- Open Mathtype demo on: https://ckeditor.com/mathtype/#demo-mathtype
- double click one of the existing formulas
- the editor opens and works but there is an error in the console:
```
ck-demo-external-mathtype-747bcd19fc.js:7569 Error tracking OPENED_MTCT_EDITOR TypeError: Cannot read properties of undefined (reading 'track')
    at ln.onOpen (ck-demo-external-mathtype-747bcd19fc.js:7569:20534)
    at Object.callback (ck-demo-external-mathtype-747bcd19fc.js:7934:6595)
    at Mn.fire (ck-demo-external-mathtype-747bcd19fc.js:7566:287017)
    at ln.insertEditor (ck-demo-external-mathtype-747bcd19fc.js:7569:17212)
onOpen @ ck-demo-external-mathtype-747bcd19fc.js:7569
(anonymous) @ ck-demo-external-mathtype-747bcd19fc.js:7934
fire @ ck-demo-external-mathtype-747bcd19fc.js:7566
insertEditor @ ck-demo-external-mathtype-747bcd19fc.js:7569
setTimeout
insertEditor @ ck-demo-external-mathtype-747bcd19fc.js:7569
insert @ ck-demo-external-mathtype-747bcd19fc.js:7569
create @ ck-demo-external-mathtype-747bcd19fc.js:7934
open @ ck-demo-external-mathtype-747bcd19fc.js:7934
openModalDialog @ ck-demo-external-mathtype-747bcd19fc.js:8018
openExistingFormulaEditor @ ck-demo-external-mathtype-747bcd19fc.js:8021
doubleClickHandler @ ck-demo-external-mathtype-747bcd19fc.js:8021
e.target.listenTo.priority @ ck-demo-external-mathtype-747bcd19fc.js:8021
fire @ ck-demo-external-mathtype-747bcd19fc.js:7557
Mo @ ck-demo-external-mathtype-747bcd19fc.js:7557
fire @ ck-demo-external-mathtype-747bcd19fc.js:7557
fire @ ck-demo-external-mathtype-747bcd19fc.js:7557
onDomEvent @ ck-demo-external-mathtype-747bcd19fc.js:7559
listenTo.useCapture @ ck-demo-external-mathtype-747bcd19fc.js:7557
fire @ ck-demo-external-mathtype-747bcd19fc.js:7557
t @ ck-demo-external-mathtype-747bcd19fc.js:7557
```
- after closing the editor another error in the console appears:
```
ck-demo-external-mathtype-747bcd19fc.js:7934 Error tracking CLOSED_MTCT_EDITOR TypeError: Cannot read properties of undefined (reading 'track')
    at F2.close (ck-demo-external-mathtype-747bcd19fc.js:7934:6893)
    at F2.submitAction (ck-demo-external-mathtype-747bcd19fc.js:7934:2793)
```
## Expected result

- no errors in the console
- 
## Actual result

errors in the console - mentioned above
https://share.cleanshot.com/h9TY9JNm
 ›

**Comment by carla-at-wiris** [comment]
Hi @usqr, thanks for writing us!

It seems that the console error is expected since a certain file was not loaded properly and then, any related code to the result of that will create the console error. 

The code raising the error does affect any of the plugin functionalities, so there's no risk that due to this error something will fail.

The demo linked is under the CKEditor5 team control, so there's not much we can do here.

Any further issues, please feel free to contact us or write an email to our support team at [support@wiris.com](mailto:support@wiris.com).

**Comment by usqr** [comment]
@carla-at-wiris Can you help me how to find the file that the plugin can't access? (I am web dev that takes care of those demos 😅 )
