### ISSUE TITLE
[Ipad][ckeditor5] when wiris popup is open in both portrait and landscape then its inserting at the beginning of the line not where the cursor is,

### ISSUE THREAD

**Issue by amitjangid12** [wiris/html-integrations#1042]
## Description

_What does the bug consist in?_

## Environment

_Which version of MathType does this happen in?_

_What is the relevant software and their versions?_

- _Editor (CKEditor, Froala, TinyMCE, etc.)_
- _Framework (Angular, React, etc.)_
- _Browser (Chrome, Firefox, etc.)_
- _Operating System (Windows, macOS, Ubuntu, etc.)_

## Steps to reproduce

_What are the steps needed to reproduce the bug?_
_Please be specific._

## Expected result

_What is the expected outcome of the steps above?_

## Actual result

_What is the actual outcome of the steps above?_

## Other details

_Is there anything else to consider?_

**Comment by usantos-at-wiris** [comment]
Hey, @amitjangid12 could you please fill up the form, so we can take a deeper look at your issue? Thanks for reporting!

**Comment by amitjangid12** [comment]
@usantos-at-wiris which type of fill up the form
