### ISSUE TITLE
modelWriter.createElement() is not a function

### ISSUE THREAD

**Issue by Arthur944** [wiris/html-integrations#112]
I got this error every time I tried to use the plugin. Solution was to change plugin.js line 219:
```
- return modelWriter.createElement('mathml', {...
+ return modelWriter.writer.createElement('mathml', {...
```

**Comment by xaviripo** [comment]
Hi!

We are going to take a look at this issue as soon as possible. Could you please offer a little bit more detail? For example, specific versions of the CKEditor packages and the MathType plugin, and what steps are necessary to reproduce the error?

Thank you.

**Comment by carlawiris** [comment]
We have released a new version that solves this bug, it is the 7.26.0
