### ISSUE TITLE
[CKEditor 5] CKeditor error: "Cannot read property 'name' of undefined" when trying to edit the formula on a TodoList

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#12]
Tested on new version, branch `ckeditor5-demo`

#### Steps to reproduce:
   - add MathType formula as an item on TodoList
   - double-click on the formula to open MathType editing window
   - click `ok` in MathType editing window

Result:
   
   ```js
   Uncaught TypeError: Cannot read property 'name' of undefined
    at Mapper.getModelLength (mapper.js:485)
    at Mapper._findPositionIn (mapper.js:550)
    at Mapper.on.priority (mapper.js:107)
    at Mapper.fire (emittermixin.js:209)
    at Mapper.toViewPosition (mapper.js:334)
    at DowncastDispatcher.<anonymous> (downcasthelpers.js:399)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher.convertRemove (downcastdispatcher.js:213)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:139)
    at editingcontroller.js:92
   ```

**Comment by carlawiris** [comment]
This issue can no longer be reproduced, so we assume it's solved.
But we detected that the todo-list plugin has positioning issues:

![ck5issue](https://user-images.githubusercontent.com/60604864/95436322-ff97b500-0953-11eb-82f2-c9c7739c4683.png)
As you can see in the first image, there is an all-list created but the items in the list boxes do not render well, however, if you overlay the later image by aligning the items to the center of the editor, they look good:

![issueck52](https://user-images.githubusercontent.com/60604864/95436995-c3b11f80-0954-11eb-827f-3dc7e753e92d.png)

**Comment by FilipTokarski** [comment]
Thank you for reporting this. I'm not able to reproduce this positioning issue in any environment, so I suppose it's nothing critical for now, however I'll keep this in mind. 
   
As it comes to the original issue, I'm also unable to reproduce it. It looks like it's been fixed and we can close this ticket as solved.

**Comment by carlawiris** [comment]
Thank you!
