### ISSUE TITLE
Error after inserting formula and typing in Ckeditor 5

### ISSUE THREAD

**Issue by mnadeaufbo** [wiris/html-integrations#145]
To reproduce
1 - Use CKeditor 5 with MathType
2 - Insert any formula
3 - Type anything
The error : Uncaught CKEditorError: e.createElement is not a function
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-e.createElement is not a function
![pbWiris](https://user-images.githubusercontent.com/76120516/102461518-c6ad4800-4048-11eb-892d-4bfc49ba0147.gif)

**Comment by xaviripo** [comment]
Hi! Thanks for reporting this issue. We will take a look at it as soon as we can.

Could you please let us know which versions of MathType and CKEditor 5 are you using?

**Comment by mnadeaufbo** [comment]
Here is the package.json
`{
  "name": "ckeditor5-custom-build",
  "author": "CKSource",
  "description": "A custom CKEditor 5 build made by the CKEditor 5 online builder.",
  "version": "0.0.1",
  "license": "SEE LICENSE IN LICENSE.md",
  "private": true,
  "devDependencies": {
    "@ckeditor/ckeditor5-alignment": "^23.1.0",
    "@ckeditor/ckeditor5-autoformat": "^23.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^23.1.0",
    "@ckeditor/ckeditor5-block-quote": "^23.1.0",
    "@ckeditor/ckeditor5-ckfinder": "^23.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^23.6.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^23.6.0",
    "@ckeditor/ckeditor5-editor-classic": "^23.1.0",
    "@ckeditor/ckeditor5-essentials": "^23.1.0",
    "@ckeditor/ckeditor5-font": "^23.1.0",
    "@ckeditor/ckeditor5-heading": "^23.1.0",
    "@ckeditor/ckeditor5-highlight": "^23.1.0",
    "@ckeditor/ckeditor5-horizontal-line": "^23.1.0",
    "@ckeditor/ckeditor5-image": "^23.1.0",
    "@ckeditor/ckeditor5-indent": "^23.1.0",
    "@ckeditor/ckeditor5-link": "^23.1.0",
    "@ckeditor/ckeditor5-list": "^23.1.0",
    "@ckeditor/ckeditor5-media-embed": "^23.1.0",
    "@ckeditor/ckeditor5-paragraph": "^23.1.0",
    "@ckeditor/ckeditor5-paste-from-office": "^23.1.0",
    "@ckeditor/ckeditor5-remove-format": "^23.1.0",
    "@ckeditor/ckeditor5-special-characters": "^23.1.0",
    "@ckeditor/ckeditor5-table": "^23.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^23.1.0",
    "@ckeditor/ckeditor5-typing": "^23.1.0",
    "@ckeditor/ckeditor5-upload": "^23.1.0",
    "@wiris/mathtype-ckeditor5": "^7.24.1",
    "css-loader": "^5.0.0",
    "postcss": "^8.1.4",
    "postcss-loader": "^4.0.4",
    "raw-loader": "^4.0.2",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^4.2.3",
    "webpack": "^4.44.2",
    "webpack-cli": "^4.1.0"
  },
  "scripts": {
    "build": "webpack --mode production"
  }
}`

**Comment by xaviripo** [comment]
Hi,

Sorry for the late response. As of MathType 7.26.1, this error cannot be reproduced anymore.
