### ISSUE TITLE
[CKEditor 5] Problems with copy&paste

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#15]
Tested on new version, branch `ckeditor5-demo`

I'm not able to copy&paste a formula, but able to cut. Moreover, if you add Image plugin, the formula will be copied, but pasted as an image.

**Comment by carlawiris** [comment]
@FilipTokarski in the latest version of the plugin this problem is solved. If there are any other similar bugs, there is the following issue you can refer to: https://github.com/wiris/html-integrations/issues/96
