### ISSUE TITLE
Is there a way to integrate wiris plugin with Quill editor?

### ISSUE THREAD

**Issue by mca-binita** [wiris/html-integrations#151]
I am looking for a way to insert Maths formulas in one of my applications built for a school.
We are using Quill editor to write text in the application as CKEditor and tinyMCE are very expensive.
We tried to integrate wiris plugin with Quill editor with no success. 
Can you please suggest a way to do so?

**Comment by carlawiris** [comment]
Hello @mca-binita, thank you for the question.

We suggest you to try doing the integration with the generic package. It's prepared and designed to be integrated in any type of editor. In parallel we will try to make the integration example as soon as we have the time.

**Comment by mca-binita** [comment]
Thank you very much for your reply.
I will try to do so as per your suggestion.
