### ISSUE TITLE
Is there a way to set default placeholder in popup?

### ISSUE THREAD

**Issue by ivanromakh** [wiris/html-integrations#153]
Hi.
I have small issue about placeholder in popup. Is there a way to set placeholder there?
![image](https://user-images.githubusercontent.com/18567511/94143168-234cfc80-fe78-11ea-92ab-07adcbf4a28f.png)
Thanks.

**Comment by carlawiris** [comment]
Hello @ivanromakh, thank you for reaching us but i'm afraid we will need more information to understand your issue. Could you please provide more details about what you expect to happen?

**Comment by dcanet-at-wiris** [comment]
Hello @ivanromakh, 

This is quite an old issue and we're proceding to close it.

If you have any more question, feel free to ask.

Kind regards,

D.
