### ISSUE TITLE
Issue with using the plugin in CKEditor 5 in developer mode

### ISSUE THREAD

**Issue by vaibhavbhuva** [wiris/html-integrations#154]
I am trying to test this plugin with ckeditor5 by creating a local index.html file and loading it using parcel-bundler. I am getting the following error:
![image](https://user-images.githubusercontent.com/36467967/69807557-9c090b00-120b-11ea-8224-ac6f123cc1de.png)

My sample html code is below:
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>CKEditor</title>
    <script src="https://cdn.ckeditor.com/ckeditor5/15.0.0/classic/ckeditor.js"></script>
    <script src="../src/plugin.js"></script>
</head>

<body>
    <textarea name="content" id="editor">This is some sample content.</textarea>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'), {
                plugins: ['MathType'],
                toolbar: {
                    items: [
                        'MathType',
                        'ChemType',
                    ]
                },
            })
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });
    </script>
</body>

</html>
```

Please advice, how can I test this with ckeditor5 locally such that I can step through the code.

**Comment by carlawiris** [comment]
Hello, Thank you for your report and sorry for the late response. 

We'll take a look at your issue and we'll come back to you once we have some news on it.

**Comment by carlawiris** [comment]
Hello @vaibhavbhuva , thanks for your patience.

We recommend you to take a look at the [html-integrations/demos](https://github.com/wiris/html-integrations/tree/stable/demos) section for a specific demo with the CKEditor5 integration. You can find it in the html5/ckeditor5 specific folder.
You also can read this [guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor) to find more information about the way you're trying to add the mathtype plugin on CKEditor5.

If you have more doubts, please contact us.
