### ISSUE TITLE
How can I customize toolbar and items at Chemtype

### ISSUE THREAD

**Issue by jongjunpark** [wiris/html-integrations#155]
Hi,

Recently, I have developed some editor by using react. and I used mathtype in ckeditor5.
this plugin is very cool and convenient.
so I need mathtype.

 
however, I have a problem I used this super cool plugin.
I just want to customize toolbar and items in Chemtype.
so I tried to change some code in "node_modules/wiris/mathtype-html-integration-devkit/src/core.src.js" (below image)
![image](https://user-images.githubusercontent.com/60080679/107474612-f9417000-6bb5-11eb-8106-e4cd3147436d.png)

I changed toolbar string so this code can change toolbar. It was Awesome! 
![image](https://user-images.githubusercontent.com/60080679/107474628-08c0b900-6bb6-11eb-89a0-1ccd6365dd9b.png)

However, It didn't insert equation in editor by clicking insert button.
I faced below error. I can't solve this problem.
please tell me how can I fix the this problem or another way to customize Chemtype's toolbar and Items. 
![image](https://user-images.githubusercontent.com/60080679/107474647-124a2100-6bb6-11eb-83d2-4d298f626b37.png)

**Comment by carlawiris** [comment]
Hi @jongjunpark, thank you for contacting us about your questions.

I regret to inform you that currently the possibility to change the toolbar as you ask is not available, it is code that we do not give the possibility to change. But if you need or want to try to make changes, you can keep modifying the code from the node_modules and investigate on your own.
