### ISSUE TITLE
Preview Popup not showing maths formulas for tinymce

### ISSUE THREAD

**Issue by SIMRAN88** [wiris/html-integrations#156]
Hi There, We were facing this linked issue where we need some help from you guys.

https://github.com/tinymce/tinymce/issues/6271#event-4188691481

**Comment by carlawiris** [comment]
Hello, thank you for reaching us.

The specific TinyMCE "preview" plugin is not designed to render formulas, at least not the ones we use with MathType. To be able to do it, we have created a function that does the same as the preview plugin but being able to render the formulas.

1. First you have to add as a dependency of your project the following script: 
`<script src="https://www.wiris.net/demo/plugins/app/WIRISplugins.js?viewer=image"></script>`
>From a JavaScript file you can do it in the following way:
```
const jsDemoImagesTransform = document.createElement('script');
jsDemoImagesTransform.type = 'text/javascript';
jsDemoImagesTransform.src = 'https://www.wiris.net/demo/plugins/app/WIRISplugins.js?viewer=image';
document.head.appendChild(jsDemoImagesTransform);
```

2. Then use the following function
   ` com.wiris.js.JsPluginViewer.parseElement(content)` where **content** is the content of the editor you want to preview.

3. You can create a button and assign this functionality to it or, if you know how, customize the TinyMCE preview plugin to use our library that renders the mathematical formulas.

If you want to see a live example of this library, you can check our html5+TinyMCE5 demo in this repository.
