### ISSUE TITLE
[CKEditor 5] Able to modify formula in read-only mode

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#158]
Original issue: https://github.com/ckeditor/ckeditor5/issues/9073

## Steps to reproduce:
1. Add formula to the editor
2. Enable read only mode: `editor.isReadOnly = true`
3. Double click on the formula

## Expected behavior:
MathType window does not open.

## Actual behavior:
MathType window opens, you can modify and save the formula.

## Screencast:

https://user-images.githubusercontent.com/34380544/108821508-fbe09400-75bd-11eb-80ce-d8da2de518d0.mp4

## Other info:
- browser: any
  
Tested on:
- MathType version `7.24.4`
- CKEditor plugins version `25.0.0`

**Comment by carlawiris** [comment]
Hello, thank you for reporting this issue.

We will add it to our backlog and let you know once we start working on it, once it's solved and which version of the plugin has the solution.

**Comment by carla-at-wiris** [comment]
The issue has been solved in the last released version, number 7.27.0. 

If something else comes up, please feel free to contact us.
