### ISSUE TITLE
[CKEditor 5] Upcast converter tries to convert all span view elements

### ISSUE THREAD

**Issue by markcharyk** [wiris/html-integrations#17]
If you try to use the `mathtype-ckeditor5` plugin in an editor with `span`s that do not have `class="ck-math-widget`, the plugin will try to upcast them anyways.

So to repro, create a simple custom plugin with the following conversion:
```
this.editor.conversion.for('upcast').elementToElement({
  view: {
    name: 'span',
    attributes: {
      'data-role': 'not-math'
    }
  },
  model(viewElement, modelWriter) {
    return modelWriter.createElement('span');
  }
});
```
If you install both plugins and try to call `editor.setData('<p>Here is an <span>error</span>.</p>);` you end up with an error of:
```
 viewElement.getChild(...).getAttribute is not a function
```

**Comment by xaviripo** [comment]
This was fixed in ae343f8.
