### ISSUE TITLE
[CKEditor 5] Mathtype adds extra br elements to the output markup

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#2]
Original issue - https://github.com/ckeditor/ckeditor5/issues/2013.

## Steps to reproduce

1. Use an editor with mathtype and table plugins.
2. Add a 2x2 table.
3. Call `editor.getData()`.

## Expected result

Table markup without `br`s.

```html
<table>
	<tbody>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
```

## Actual result

Returned table has some extra `br`s in it.

```html
<table>
	<tbody>
		<tr>
			<td><br data-cke-filler="true"></td>
			<td><br data-cke-filler="true"></td>
		</tr>
		<tr>
			<td><br data-cke-filler="true"></td>
			<td><br data-cke-filler="true"></td>
		</tr>
	</tbody>
</table>
```

**Comment by xaviripo** [comment]
Solved as of [MathType for CKEditor 5 version 7.19.0](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5/v/7.19.0).
