### ISSUE TITLE
[CKEditor 5] Firefox - cursor not showing up/not able to type after adding comment to MathType equation

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#22]
Original issue: https://github.com/ckeditor/ckeditor5/issues/6473

### Steps to reproduce:
1. Open editor with MathType and Comment plugins
2. In empty line add a MathType equation
3. Select the equation and add a comment
4. Click after the equation and try to type

### Expected result:
Cursor shows up, you are able to type

### Actual result:
Cursor is not showing up, you can't type. In order to see it and type, you have to click on equation and press `arrow-right`:
![23_FF3](https://user-images.githubusercontent.com/34380544/77330744-0e07e180-6d20-11ea-9b01-995fef23e893.gif)

### Other details
- Browser: Firefox, works fine in other browsers

**Comment by carla-at-wiris** [comment]
Hello @FilipTokarski, we are sorry for the late response.

This issue is no longer reproducible in the latest versions of both plugins: mathtype-ckeditor5 and CKEditor5 comments ones.

**Comment by FilipTokarski** [comment]
Hi, I checked it and can still reproduce the original issue. I'm using CKEditor5 `31.1.0` and MathType `7.27.2`:


https://user-images.githubusercontent.com/34380544/147917680-8a1b0aab-a5c5-45d8-8e66-e0c714888d63.mp4
