### ISSUE TITLE
How can I get images by asynchronized method in version 5?

### ISSUE THREAD

**Issue by jongjunpark** [wiris/html-integrations#227]
Hello, I used mathtype-ckeditor5 very well.

However, when I insert a lot of quantity about >100, I was so late on renderring due to synchronized method.

<img width="635" alt="스크린샷 2021-04-20 오후 3 49 23" src="https://user-images.githubusercontent.com/60080679/115643046-05387380-a357-11eb-9996-f606da51c3fd.png">

So I tried I get images by using asynchronized method in [this page's way](https://docs.wiris.com/en/mathtype/mathtype_web/integrations/mathml-mode)

but I think, this page work on ckeditor4 or lower version. 
If my method is wrong, please let me know the method in detail.

Otherwise, I want to know another way about asynchronized load in ckeditor5-mathtype.

**Comment by xaviripo** [comment]
Thanks for contacting us. I have transfered this issue to our new repository, wiris/html-integrations#227.

Currently, there is no way to use async loading *inside* the editor. The instructions that you linked to apply to formulas rendered *outside* of the editor, using the `WIRISplugins.js` file. To have an async render of formulas outside of the editor, add `async=true` to the `script` tag:

```html
<script src="https://www.wiris.net/demo/plugins/app/WIRISplugins.js?viewer=image&async=true"></script>
```

**Comment by dcanet-at-wiris** [comment]
Hi, @jongjunpark 

Thanks for reaching.

We are proceding to close the issue.

Kind regards,

D.
