### ISSUE TITLE
Redo button is broken in tinymce rich text toolbar when there is Wiris in content

### ISSUE THREAD

**Issue by nct124** [wiris/html-integrations#275]
Replicable in https://demo.wiris.com/integrations/tinymce/
1. make changes to richtext content
2. undo button is enabled
3. click on undo button

**Expected result**
redo button should be enabled
**Actual result**
redo button is still disabled

**Comment by carla-at-wiris** [comment]
The issue has been solved in the last released version, number 7.27.0. 

If something else comes up, please feel free to contact us.

**Comment by nct124** [comment]
hi there are still some issues with the redo feature
https://demo.wiris.com/integrations/tinymce/
steps:
1. Add new wiris equation
2. undo (equation removed)
3. redo

**Expected outcome**

- removed wiris equation is added back

**Actual outcome**

- redo does nothing

**Comment by carla-at-wiris** [comment]
Thank you for your feedback, this issue solution has been added to our next release version.

We'll keep you posted.
