### ISSUE TITLE
[Android tablet][tinymce] wiris toolbar is cut off when wiris popup is open in both portrait and landscape

### ISSUE THREAD

**Issue by nct124** [wiris/html-integrations#276]
replicable in https://demo.wiris.com/integrations/tinymce/
1) Use an Android tablet
2) Insert math equation or chem equation
3) notice that the toolbar that was on the top, is cut off and not accessible at all

![_thumb_32604](https://user-images.githubusercontent.com/22850091/121279265-e2fab500-c906-11eb-829e-e721e759d4ef.png)

**Comment by xripoll-at-wiris** [comment]
Hi! Sorry for the late response. We are working on properly reproducing your issue. We will get back to you as soon as we have any fix or need more information.

**Comment by icaparros-at-wiris** [comment]
Hi @nct124, This bug has been fixed on the version 7.28.0.

I proceed to close the issue.
