### ISSUE TITLE
[tinymce] formula display incorrectly when using Left Superscript

### ISSUE THREAD

**Issue by nct124** [wiris/html-integrations#287]
replicable on https://codesandbox.io/s/tinymcevue-forked-tr0yo?file=/src/tinymce.js

1. Create a math formula using "Left Superscript"
2. After my system save the content
content saved: `<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mmultiscripts><mi>C</mi><mprescripts></mprescripts><none></none><mn>13</mn></mmultiscripts></math>`
3. content was reload into the editor component but the math fomula was displayed incorrectly.

correct display
![correct](https://user-images.githubusercontent.com/22850091/123908704-7a08d900-d9aa-11eb-9cda-07b0ab458953.PNG)
incorrect display
![incorrect](https://user-images.githubusercontent.com/22850091/123908729-842ad780-d9aa-11eb-9b1d-ddd850eb42ec.PNG)

**Comment by carla-at-wiris** [comment]
Thank you @nct124 for reporting this issue.

This issue has already been detected and is being resolved. We'll keep you updated when the solution comes live.

**Comment by carla-at-wiris** [comment]
The issue has been solved in the last released version, number 7.27.0. 

If something else comes up, please feel free to contact us.
