### ISSUE TITLE
[CKEditor 5] Wiris MathType plugin is not working with ckeditor5 in React/Vue

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#3]
Original issue - https://github.com/ckeditor/ckeditor5/issues/2048.

![Schermafdruk 2019-09-13 11 52 59](https://user-images.githubusercontent.com/49290062/64854106-271b3180-d61d-11e9-9a12-9f08fa280e0c.png)

I simply try to implement the MathType plugin following this documentation: 
- https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html
- https://ckeditor.com/docs/ckeditor5/latest/features/mathtype.html#usage

I'm getting an error and this only happens when i try to implement the MathType plugin. I'm not sure if i'm missing any config settings that i have to parse to
initialize the plugin but reading trough the documentation i'm not seeing anything i'm missing. Maybe I have to buy a licence or something??

## Steps to reproduce

1. Clone this Repo: https://github.com/mstermaaten/CKEditor-Issue
2. npm i && npm start

## Expected result

![Schermafdruk 2019-09-13 11 56 03](https://user-images.githubusercontent.com/49290062/64854336-b45e8600-d61d-11e9-935a-a200ff2b7cc3.png)

**Comment by carlawiris** [comment]
We've reviewed the code on [the repository you provide](https://github.com/mstermaaten/CKEditor-Issue) and I won't suggest to do it that way becasue the CKEditor5 plugin will not allow duplicated modules when importing MathType plugin.

I'd suggest to have a look to the [examples for developers on how to integrate MathType](https://github.com/wiris/html-integrations/tree/stable/demos/) on CKEditor.

There's an specific example for CKEditor5 with React, on the following link: https://github.com/wiris/html-integrations/tree/stable/demos/react/ckeditor5.

If you run the demo you'll see that it works fine and there are no error on the console.

You can also follow the step by step instructions on the same folder README file to build the demo from scratch.

If you have any doubt, you can contact us here or through our support email: support@wiris.com.
