### ISSUE TITLE
Too much loading and fluctuation in iPad 6 generation

### ISSUE THREAD

**Issue by sandeep-6698** [wiris/html-integrations#346]
i am using wiris external plugin in ckediror4-react and its working fine in window and as well as macOs chrome and  safari browser but in iPad 6 it's not working as expected. it taking too much time or some time not able to close the wiris editor modal window after inserting any symbols. 

## Other details

* Browser: Safari
* OS: iOs
* Integration version: ckeditor4-react 
* CKEditor version: ckeditor-4
* Installed CKEditor plugins: wiris

**Comment by carla-at-wiris** [comment]
Hello @sandeep-6698 , thank you for reaching us with your issue.

We would need more information about it, for example, which react, ckeditor4 and wiris versions are you using, how much time is exactly taking the wiris modal to close (secosn, minutes, ...).

**Comment by carla-at-wiris** [comment]
This issue was closed because it has been inactive for 14 work days since more information was requested.
