### ISSUE TITLE
List of editor events

### ISSUE THREAD

**Issue by doox911** [wiris/html-integrations#356]
Hi. Can't find a list of all available editor events anywhere (Wiris Generic Plagin). The only event I could find in the documentation and in the code is `onTargetReady`.

Tell me how to see the following events: 
- Insert 
- Cancel 
- Change content after insertion

and so on?

**Comment by xripoll-at-wiris** [comment]
Hi! Thanks for contacting us.

We are currently working on a full-fledged online documentation for our API. Right now, unfortunately, there is no exhaustive list of the events we fire. You can find them by looking for calls to the `packages/mathtype-html-integration-devkit/src/listeners.js#fire` method. These will also show how to apply new listeners.

For your specific need, you might be interested in the `onInit`, `onBeforeFormulaInsertion`, and `onAfterFormulaInsertion` events.

**Comment by doox911** [comment]
```
const properties = this.wirisGenericProperties();

const wiris_generic = new window.WirisPlugin.GenericIntegration(properties);

const onAfterFormulaInsertion = wiris_generic.listeners.constructor.newListener('onAfterFormulaInsertion', () => {
  console.log('onAfterFormulaInsertion');
});

wiris_generic.listeners.add(onAfterFormulaInsertion);

wiris_generic.init();

window.WirisPlugin.currentInstance = this.wiris_generic;

wiris_generic.listeners.fire('onTargetReady', {});

wiris_generic.listeners.fire('onAfterFormulaInsertion', {});

function wirisGenericProperties() {
  const target = document.getElementById('wiris-content');

  if (!target) {
    throw new Error('Undefined target from Wiris Generic');
  }

  const toolbar = document.getElementById('toolbar-location');

  if (!toolbar) {
    throw new Error('Undefined toolbar from Wiris Generic');
  }

  return {
    target,
    toolbar,
  };
}
```
The callback function does not fire. What am I doing wrong?

**Comment by xripoll-at-wiris** [comment]
In your example, you are creating a new instance of the integration, which isn't related to the one attached to the editor at all. You have to add a listener to the existing instance, which can be accessed via the global `WirisPlugin.currentInstance`. Try the following snippet:

```js
WirisPlugin.currentInstance.core.listeners.add(Listeners.newListener('onAfterFormulaInsertion', () =>
   console.log('onAfterFormulaInsertion');
}));
```

The class `Listeners` can be imported from `@wiris/mathtype-html-integration-devkit/src/listeners`.

**Comment by dcanet-at-wiris** [comment]
Hola @doox911 

How are you?

Did you had the chance to try the fix @xaviripo provided?

We'll be closing the issue if it's ok for you.

Thanks!

**Comment by doox911** [comment]
Hola @dcanet-at-wiris

I beg your pardon. There was no way to check yet. I think you can close.

**Comment by dcanet-at-wiris** [comment]
No worries!

Many thanks for reporting.

Kind regards.
