### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by Octo216** [wiris/html-integrations#357]
Hi there)
Would highly appreciate your help with issue which bothers me during last time.
In our Angular project we are using Froala Editor together with Wiris.

*Issue is:*
When user clicks Wiris icon in froala toolbar _Uncaught TypeError: Illegal invocation_(Chrome) error appears in console, possibly as a result of this error formula pasting doesn't trigger froala _contentChanged_ hook and user content itself didn't saving properly.

In Safari and Firefox errors has slightly different wording but same behaviour:
Safari: _TypeError: Can only call Element.closest on instances of Element_
Firefox: _Uncaught TypeError: 'closest' called on an object that does not implement interface Element._

## Environment
"@angular/core": "~12.0.1",
"@wiris/mathtype-froala3": "~7.24.3",
"angular-froala-wysiwyg": "~3.2.3",
"froala-editor": "~3.2.3",

- *Framework (Angular 12)*
- *Browser (Chrome, Firefox, Safari, ...)*
- *Operating System (Windows, macOS)*

## Steps to reproduce
1) Click Wiris button in Froala toolbar;
2) Observe error in console;
3) Optionally debug _contentChanged_ hook is triggered

## Expected result
Formula pasting triggers _contentChanged_ hook

## Actual result
Formula pasting doesn't triggers froala _contentChanged_ hook 

## Screenshots of errors:
<img width="542" alt="Screenshot 2021-08-13 at 21 39 24" src="https://user-images.githubusercontent.com/43548355/129404925-959e9ca3-9d15-4b0b-b7d3-6073e16b3bcb.png">
<img width="355" alt="Screenshot 2021-08-13 at 21 39 32" src="https://user-images.githubusercontent.com/43548355/129404936-23a35245-2726-419b-9cc6-e8bb191e72b0.png">
<img width="536" alt="Screenshot 2021-08-13 at 21 41 44" src="https://user-images.githubusercontent.com/43548355/129404938-004951f0-00b5-493d-9c4a-7154e9ba1007.png">

**Comment by carla-at-wiris** [comment]
Hello @Octo216, thank you for contacting us.

We did a research with the information you provided us, and we have a bug on our side on the mathtype-froala3 plugin. The bug has been added to our backlog and we expect to work on it as soon as possible. 

We hope this situation does not block your project and will keep you updated on any solutions we apply on this.

**Comment by Octo216** [comment]
Thank you for response!
Unfortunately we facing this issue in one of the most requested functionality, which needs to be restricted for now..

It would be awesome if you could share estimation on when this issue might be fixed?

**Comment by dcanet-at-wiris** [comment]
Hi @Octo216 

We're currently working on it and we expect to release fix a soon.

Keep you posted.

**Comment by carla-at-wiris** [comment]
Hi @Octo216,

We are happy to inform you that this issue has been solved in our latest version, number 7.27.1.
