### ISSUE TITLE
CKEditor - MathML error

### ISSUE THREAD

**Issue by mca-binita** [wiris/html-integrations#382]
## Description

*What does the bug consist in?*
Upon trying to create a formula with MathML plugin with **CKEditor5**, it is showing error: 
**FREE TRIAL EXPIRED
#Ref62635 #0
Please contact WIRIS at sales@wiris.com in order to use this product.**

(1) I understand that I need to subscribe for the MathML service. but After subscribing, what in my ckeditor code needs to be changed in order to send correct subscription status the wiris server?

(2) right now, Mathml service points to **https://www.wiris.net/demo/editor/......** .. Is this correct?  

## Environment

*Which version of MathType does this happen in?* 

*What is the relevant software and their versions?* 

- *Editor (CKEditor, Froala, TinyMCE, etc.)* CKEditor
- *Framework (Angular, React, etc.)* Angular
- *Browser (Chrome, Firefox, etc.)* All
- *Operating System (Windows, macOS, Ubuntu, etc.)* Deployed on Linux

## Steps to reproduce

*What are the steps needed to reproduce the bug?*
*Please be specific.*

## Expected result

*What is the expected outcome of the steps above?*

## Actual result

*What is the actual outcome of the steps above?*

## Other details

*Is there anything else to consider?*

**Comment by dcanet-at-wiris** [comment]
Hi @mca-binita 

Thanks for reaching us.

MathType services can be used for free up to a certain level of uses per natural year. 

> You may find more information about conditions and prices at [MathType store](https://www.wiris.com/en/pricing/).

You should contact our sales department at sales@wiris.com with the Reference 62635, so they can register your account on the licensing system. 

Kind regards,

D.
