### ISSUE TITLE
Get latex from the Mathtype editor

### ISSUE THREAD

**Issue by henok-outlier** [wiris/html-integrations#383]
<img width="777" alt="Screen Shot 2021-08-31 at 1 17 52 PM" src="https://user-images.githubusercontent.com/72997506/131638743-b9c73d92-484a-4660-9eda-a1d4d032922c.png">

How to insert the latex format from mathtype editor when `Insert` button clicked? Is there a way to change Mathtype editor output format to `Latex`, currently it is `MathML`.

Similar to the demo here(https://demo.wiris.com/mathtype/en/developers.php), the Mathtype editor content is exposed in both MathML and Latex format, 

<img width="1444" alt="Screen Shot 2021-08-31 at 4 46 33 PM" src="https://user-images.githubusercontent.com/72997506/131654045-e76770ce-0006-48a1-9fa4-6c0ae865f5fc.png">

Thanks!

**Comment by carla-at-wiris** [comment]
Hi @henok-outlier, thank you for reaching us.

MathType editor accepts both latex and mathml, and transforms it to a rendered formula.
You can copy and paste your latex formulas on the MathType editor but you can also insert latex formulas on you text editor following this structure: $$[latex formula]$$ and the mathtype editor will be able to recognize them. Checkout the example below:
![githubissue383](https://user-images.githubusercontent.com/60604864/131698445-47f0ad63-de4e-439c-948a-da0ce64a0fa9.png)

If you're looking for a feature that, once the insert button is pressed, it introduces the formula as latex, you can capture the insert event and transform the formula to latex using our API services: WirisPlugin functions. For example: WirisPlugin.Latex.getLatexFromMathML(mathml). You can find **more information** [here](https://docs.wiris.com/api/integrations/jsdoc/api.html#section-Latex).

**Comment by henok-outlier** [comment]
Hi @carla-at-wiris , thank you for your helpful answer.

```
export const addWirisPlugin = CKEDITOR => {
  CKEDITOR.plugins.addExternal('ckeditor_wiris', '/ckeditor-mathtype/mathtype-ckeditor4/', 'plugin.js')
}
```

I've integrated Mathtype in my CKEditor4 editor using as an extra plugin from `node_modules`. How can I access the wiris API services and also the event when `Insert` button is clicked?

Thanks!

**Comment by carla-at-wiris** [comment]
Hello @henok-outlier,

You can take a look at the answer given by Xavier Ripoll on [this issue thread](https://github.com/wiris/html-integrations/issues/356), it'll answer you how to capture the insert event (specifically, fired after clicking the insert button).

Regarding the [API services](https://docs.wiris.com/api/integrations/jsdoc/api.html#), there's an object called WirisPlugin, which is public in the window to use it once the editor is loaded. For what you say, you might find interesting to use the following API functions:

- `WirisPlugin.Parser.codeImgTransform(html,code)`
- `WirisPlugin.Latex.getLatexFromMathML(mathml)`

Example:
```js
WirisPlugin.currentInstance.core.listeners.add(Listeners.newListener('onAfterFormulaInsertion', (params) => {
    const mathml = WirisPlugin.Parser.codeImgTransform(params.node.outerHTML, 'img2mathml');
    const latex = WirisPlugin.Latex.getLatexFromMathML(mathml);
    console.log(latex);
  }));
```

**Remember** to use the WirisPlugin object on the `'instanceReady'` event from CKEditor4 to make sure the object is used once the editor and Wiris plugin are ready.

**Comment by henok-outlier** [comment]
Hi @carla-at-wiris, awesome, I can able to get the latex of the added math expression.

<img width="1792" alt="Screen Shot 2021-09-07 at 5 14 13 PM" src="https://user-images.githubusercontent.com/72997506/132360216-919a2dfd-a4a7-4c45-882f-ec15f9f69e9c.png">

I want the latex to be saved in the CKEditor, as you can see in the screenshoot the expression is saved as MathML, but I want to save the latex when insert button is clicked. How can I do that?

Thank you!!

**Comment by carla-at-wiris** [comment]
Hi, @henok-outlier, 

When you catch the `onAfterFormulaInsertion` event and retrieve the `params` object, it is giving you the inserted formula with all its information. With that, you only need to set the obtained latex to the object inside the function, it should look similar to this:
```js
params.node.outerHTML = latex;
```

 

We hope this tip answers your question.

Nonetheless, it would be more appropriate to contact our Support team at support@wiris.com for this kind of questions.
The MathType SDK is an Open-source project and this repository is meant for contributions and manage the issues reported by the community.
If you don't mind, we'll proceed to close this issue to avoid mixing different topics.

Thanks for reaching us, and feel free to contact us again any time

**Comment by henok-outlier** [comment]
Hi @carla-at-wiris , please check my two questions related to the above answer. Thank you so much for your cooperation, 🙏.
