### ISSUE TITLE
[CKEditor 5] How do I convert mathtype to img

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#4]
Original issue - https://github.com/ckeditor/ckeditor5/issues/2073.

>Math appears as an image in the editor, and converting to HTML will be mathml, which I hope will not be converted

**Comment by jswiderski** [comment]
When going through internet, I have found https://stackoverflow.com/questions/35031134/wiris-editor-save-as-img-src-instead-of-mathml-in-ckeditor. @wirismath is there any way to set this configuration setting from CKEditor 4 or 5 level?

**Comment by xaviripo** [comment]
Hi @jswiderski, there currently is no way to set this from the front-end side, the only way is to use the `wiriseditorsavemode` parameter in the back-end `configuration.ini` file.

**Comment by xaviripo** [comment]
I forgot to link the docs with a more extensive explanation of `configuration.ini`: https://docs.wiris.com/en/mathtype/mathtype_web/integrations/config-table

**Comment by utkarsh27a** [comment]
> Hi @jswiderski, there currently is no way to set this from the front-end side, the only way is to use the `wiriseditorsavemode` parameter in the back-end `configuration.ini` file.

Hey I had done the setup of server side and set wiriseditorsavemode to true, it started generating image from backend, but when I call  `ckeditorInst.getData()` it still returns math ml code for math equation. I tried different configuration(base64, png, svg) but CK editor get data method not returning image for math equations. Please share what configuration is missing from my side.
Thanks in advance
