### ISSUE TITLE
Uncaught TypeError: window.WirisPlugin.GenericIntegration is not a constructor

### ISSUE THREAD

**Issue by ruirui19** [wiris/html-integrations#450]
Hi,

I am experiencing the error like `Uncaught TypeError: window.WirisPlugin.GenericIntegration is not a constructor` when trying to make an instance 

```
{
...
    const genericIntegrationInstance = new window.WirisPlugin.GenericIntegration(
            genericIntegrationProperties
          )
    genericIntegrationInstance.init()
    genericIntegrationInstance.listeners.fire('onTargetReady', {})
 }
```
Using it for MathType Generic Integration and the version is v7.10.0
Appreciated any solution for that

**Comment by ruirui19** [comment]
Hi @carla-at-wiris,

Seems like the initial issue still existed, whenever I use the component in the very first time, it shows the error
<img width="764" alt="Screen Shot 2021-11-18 at 4 33 15 PM" src="https://user-images.githubusercontent.com/17632386/142518531-fd0f7800-95c3-4278-a17c-78233bd38a60.png"> 

I updated the version into 7.27.1 and Here is the code I am using 

```
  useEffect(() => {
    // @ts-ignore
    if (window && window.WirisPlugin) {
      const genericIntegrationProperties = {
        target: equationEditorRef.current,
        toolbar: toolbarRef.current
      }
      // @ts-ignore
      const genericIntegrationInstance = new window.WirisPlugin.GenericIntegration(
        genericIntegrationProperties
      )
      genericIntegrationInstance.init()
      genericIntegrationInstance.listeners.fire('onTargetReady', {})
      // @ts-ignore
      window.WirisPlugin.currentInstance = genericIntegrationInstance
    }
  }, [equationEditorRef])
```

Is there any reason that causing this issue? Thanks

**Comment by carla-at-wiris** [comment]
Hello @ruirui19,

I'm sorry to hear that. Unfortunately we've not been able to reproduce your last issue, so could you provide us a code Pen with your code so we can try it out?

I'm glad to hear that the `codeImgTransform` function finally worked for you.

**Comment by ruirui19** [comment]
Hi @carla-at-wiris,

This bug is not happened all the time and I finally got some hints here. When I reproduced the bug and I tried to console log 
`window.WirisPlugin`, I found `GenericIntegration` is not existed. See the attachment below:

<img width="708" alt="Screen Shot 2021-12-02 at 4 23 58 PM" src="https://user-images.githubusercontent.com/17632386/144524583-35603dc7-5088-447a-83ec-b15f4571babe.png">
 
When everything normal, I can see it within `window.WirisPlugin`... Is there any reason that this class/function could be disappeared?

**Comment by ruirui19** [comment]
I think I figured out why..

So I am also using MathType within TinyMCE and this bug will happen when I open the editor with TinyMCE with MathType first and then trying to using generic implemented MathType component..

I guess it is because when using MathType within TinyMCE, it loaded the `window.WirisPlugin` with the function for tinymce only and it blocks reloading for generic method?

here is the screenshot for what contains within `window.WirisPlugin` in generic way..

<img width="618" alt="Screen Shot 2021-12-02 at 4 58 43 PM" src="https://user-images.githubusercontent.com/17632386/144526714-983e8ab5-2a52-4973-874e-9bf732f8b7eb.png">

Is there any way I can avoid the conflicts or how to make sure it loaded the correct package when I want to use tinymce and generic mathtype in the same page?

Thanks

**Comment by carla-at-wiris** [comment]
I would suggest you to use our specific plugin, coded for TinyMCE in order to prevent this kind of behaviors.
We have a plugin for [TinyCME V5](https://www.npmjs.com/package/@wiris/mathtype-tinymce5) and another one for [TinyMCE V4](https://www.npmjs.com/package/@wiris/mathtype-tinymce4), and follow their own installation instructions.

**Comment by ruirui19** [comment]
Hi @carla-at-wiris ,

I am using the plugin for tinyMCE and the issue is once the TinyMCE with Mathtype is loaded, it will override the package for generic..I think the only way to avoid this is to use `wrsInitEditor` instead of call `new window.WirisPlugin.GenericIntegration()` directly.

I saw the above PR is to fix the image and mathml tag transition. May I know when it will be merged and released?

Thanks

**Comment by carla-at-wiris** [comment]
I recommend you to use `window.wrs_int_init` instead of `wrsInitEditor`, but like i mentioned before, instead of using the generic package for MathType, you can use the MathType TinyMCE one. 

About the changes to fix the image and MathML tag transition, they are planed to be released on next year, but we'll inform you once they're available.

**Comment by ruirui19** [comment]
Thanks so much @carla-at-wiris . Ended up with `window.wrs_int_init` and the  image and MathML tag transition is working by using this initial method.
