### ISSUE TITLE
Formula not displaying properly on the target page

### ISSUE THREAD

**Issue by eokwukwe** [wiris/html-integrations#458]
Hello. I will need help to figure out what I am doing wrong.

I am trying to use the Mathtype plugin with TinyMCE editor in a Vue application. The plugin works properly in the editor, however, the formula does not display properly on the target page. According to the instruction: 

> In order to display mathematical formulas on the target page, i.e. the page where content produced by the HTML editor will be visible, the target page needs to include the MathType script

I have added the sample script in the `index.html` file but it did not work. Anything I am missing?

Here is a link to the code I am using to test it https://codesandbox.io/s/tinymce-mathtype-dbh2r

**Comment by carla-at-wiris** [comment]
Hello @eokwukwe, thank you for reaching us.

In order to see rendered formulas on the page, you need to add the mentioned MathType script, like you did, and it'll render all the initial content once you serve you page, and will also render formulas added through MathType.

If you want to display the TinyMCE content on another target, you need to specify to the script that it needs to render, and the DOM element you want to be rendered. 
You would need to use the following code anytime you want to render the other target area:
```js
com.wiris.js.JsPluginViewer.parseElement(taget-dom-element); 
```

I believe you're updating the display-content target every time there's a change on the TinyMCE editor, then you would need to add the previous line on that code area to render the formulas.

**Comment by eokwukwe** [comment]
Thanks, @carla-at-wiris for your reply. Please I don't understand the point about the function call above.

I am using Vue.js and the application is a single-page application. So I have added the **MathType** script `<script src="https://www.wiris.net/demo/plugins/app/WIRISplugins.js?viewer=image&async=true"></script>` to the head of the `index.html` of the app, hence the script is always available on all pages (in the case of a single-page application, all rendered components). So are you saying that to render the content of the editor in any component, I will need to use the above function to target the `div` where the content is to be rendered?

For example, a typical Vue.js Single File Component SFC looks like this:
```vue
<template>
  <!-- This div renders the editor content -->
  <div class="display-content" v-html="content"></div>
</template>

<script>
export default {
  props: ["content"],  // This is the content to be render that contains the math formulas
};
</script>

<style></style>
``` 
Where and how do I  use this function `com.wiris.js.JsPluginViewer.parseElement(taget-dom-element)`. Please, your help will be greatly appreciated.

**Comment by carla-at-wiris** [comment]
As I mentioned on the previous comment, you need to use the `com.wiris.js.JsPluginViewer.parseElement(<dom-container>)` function. This function takes as a parameter the **DOM element** you want to render, i.e, the DOM element identified by `container-ID` or `container-Class`.

Taking a look at your code, I assume that the DOM element you wish to render is the one identified by the class `display-content`, so you would need to pass the DOM element identified by that class as the function parameter.

The `parseElement` function will render the content whenever you call it, so, if you want to render the text every time there's a modification on the TinyMCE text editor, you would need to call that function each time the content is modified, for example, on TinyMCE events that detect editor changes.

**Comment by dcanet-at-wiris** [comment]
Many thanks for your answer, Carla. I'm closing this issue for this question.

Many thanks to @eokwukwe for contacting.

I would suggest to contact our Support team at support@wiris.com for questions like the above, though.

Kind regards,
