### ISSUE TITLE
CKEditor 5 integration is leaking memory

### ISSUE THREAD

**Issue by oleq** [wiris/html-integrations#459]
## Description

Hi, I'm a core developer of CKEditor 5 👋 

I'd like to inform you that the `MathType` plugin for the CKEditor 5 retains (lots of) memory when the editor is destroyed. This has been brought to our team's attention by our community and causes issues with integrations that re-start the editor a lot and/or use lots of editor instances on the same page.

## Environment

* Version: `"@wiris/mathtype-ckeditor5": "^7.24.0",`
* CKEditor 5
* Tested in Chrome on Mac

## Steps to reproduce

1. Close all Chrome windows.
2. Run Chrome with a guest profile (free of add-ons, etc.), on Mac this would be `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --guest --js-flags="--expose-gc"`
3. Configure CKEditor 5 **without** `MathType`.
4. Initialize the editor, then destroy it a couple of times. **Click the Garbage Collector button after each destruction**. Make sure no references are left behind (such as `window.editor`).
5. Take a memory snapshot.
6. Repeat 4.-5. a couple of times.
7. Configure CKEditor 5 **with** `MathType` enabled.
8. Repeat 4.-5. a couple of times.

## Expected result

There should be no dramatic difference in snapshot size and retained memory.

## Actual result

The presence of the `MathType` causes the editor to leak memory which is retained after each destruction.

<img width="246" alt="Screenshot 2021-11-04 at 09 50 46" src="https://user-images.githubusercontent.com/1099479/140309032-f768f54f-146b-4ff1-9217-b0520d852f21.png">

## Other details

Related issues in CKEditor 5:
* https://github.com/ckeditor/ckeditor5/issues/10749
* https://github.com/ckeditor/ckeditor5/issues/5954

**Comment by carla-at-wiris** [comment]
Hello @oleq, 

Thank you so much for the information and for reporting the issue. We've added it on our backlog and will start working on it as soon as we can.

**Comment by icaparros-at-wiris** [comment]
Hi @oleq,

We are happy to inform you that this issue has been fixed in the [7.28.0 version](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5/v/7.28.0).

We are proceding to close the issue.
