### ISSUE TITLE
TinycMCE 5 Intergration show  " This is a TRIVAL version"

### ISSUE THREAD

**Issue by Averey** [wiris/html-integrations#465]
TinycMCE 5 Intergration show  " This is a TRIVAL version", how to config it?
![image](https://user-images.githubusercontent.com/3632515/141098440-2c574a47-c8ef-4200-9185-729b4a1b466e.png)

**Comment by carla-at-wiris** [comment]
Hello @Averey,

Thank you for reaching us. This is currently a licensing issue managed by the **sales** team. 
I suggest you to contact them through their email sales@wiris.com and send them also the image or the numbers at the bottom of the overlay (the reference numbers)
