### ISSUE TITLE
Mathtype plugin  in ckeditor 4

### ISSUE THREAD

**Issue by Shuttler97** [wiris/html-integrations#47]
There is a issue  while binding the data with  ng-model in angular js project when mathtype plugin used in ckeditor, It breaks the  whole code and data are not shown on the ckeditor. Is it unable to render the data or equation while using mathtype plugin in ckeditor ?
I'm using ckeditor 4.14 and mathtype plugin with 7.16 version

**Comment by carlawiris** [comment]
Hi, thank you for reporting this. 

I'm afraid we will need more information, for example, a list of steps to reproduce the issue, to understand better which is your problem. But we also think that maybe you can take a look at the set of code examples on how to integrate mathtype with angular at the following link: https://github.com/wiris/html-integrations/tree/stable/demos.

Here are the commands to clone and set up the demo with CKEditor:
```
html-integrations$ git clone...
html-integrations$ cd demos/angular/ckeditor5
html-integrations$ npm install
html-integrations$ npm start
```
