### ISSUE TITLE
[CKEditor 5] MathType plugin doesn't accept &amp; entity

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#5]
Original issue - https://github.com/ckeditor/ckeditor5/issues/5732.

## Steps to reproduce

Open editor with MathType plugin and execute `editor.setData('&amp;');`. 

## Expected result

Character `& ` should be displayed just like in editor without MathType plugin. 

## Actual result

Error gets thrown: `Parse error - Error parsing XML`

**Comment by xaviripo** [comment]
Solved as of [MathType for CKEditor 5 version 7.19.0](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5/v/7.19.0).
