### ISSUE TITLE
not loading https://www.wiris.net/demo/plugins/app/configurationjs in ckeditor with chrome

### ISSUE THREAD

**Issue by AliRezaHosseiniOfficial** [wiris/html-integrations#600]
## Problem loading https://www.wiris.net/demo/plugins/app/configurationjs and chrome lock because

The default ckeditor installation package is used

**There is no such problem in Firefox

*What does the bug consist in?*

## Environment

*Which version of MathType does this happen in?* ^7

*What is the relevant software and their versions?*

- *Editor (CKEditor, Froala, TinyMCE, etc.)* ckeditor 4
- *Framework (Angular, React, etc.)* etc
- *Browser (Chrome, Firefox, etc.)* chrome, edge
- *Operating System (Windows, macOS, Ubuntu, etc.)* windows

**Comment by icaparros-at-wiris** [comment]
Hey @AliRezaHosseiniOfficial,

We are unable to reproduce the bug. 

Could you please give us more information about your use case?
