### ISSUE TITLE
[CKEditor 5] Chemical formulas in version 8.0.0 disappear on drop or paste

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#683]
## Description

Chemical formulas in version `8.0.0` disappear on drop or paste

## Environment

Happens since version `8.0.0`

- CKEditor 5
- Browser: any

## Steps to reproduce

1. Go to [CKEditor 5 MathType demo](https://ckeditor.com/mathtype/#demo-mathtype)
2. Drag & drop chemical formula to some other place

## Expected result

You can drag & drop or paste chemical formulas.

## Actual result

Chemical formalas disappear. It works fine for math equations.

Tested also on other custom editor builds, not only on demo website.

## Other details

Screencast:

https://user-images.githubusercontent.com/34380544/200300959-0dee3bb9-5937-4cfa-af7a-3565cf890ac2.mov

**Comment by jguillen-at-wiris** [comment]
Hi Filip!

Thanks for your feedback.
This issue should be fixed in our coming version 8.0.1.
It will be released in the following days.
