### ISSUE TITLE
[CKEditor 5] CKEditorError: view-position-before-root: You can not make position before root

### ISSUE THREAD

**Issue by Mgsy** [wiris/html-integrations#7]
Original issue - https://github.com/ckeditor/ckeditor5/issues/5759.

This error has occurred a couple times now when setting data from firebase.

The error seems to occur when the article is high in formulas created with the MathType plugin.
But this is not the case every time, sometimes setting data with only 1 formula will trigger the error to.

The [documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-position-before-root) doesn't say a lot on how to fix or prevent this error, I was hoping you guys could give a bit more guidance in how to handle this error.

It is a bit annoying because now if the client as this error we have to go into the database and remove snippets manually...

To see a document that trows the error please click the link below to see the demo V of the CMS used to create the documents:

[https://objective-blackwell-ced0b4.netlify.com](https://objective-blackwell-ced0b4.netlify.com/)
username: test@editor.com
pw: testing

If any information is needed please let me know.

## Expected result

That any document created with the editor is able to be set as data.

## Actual result

![Schermafdruk 2019-11-19 13 00 47](https://user-images.githubusercontent.com/49290062/69146358-f7caea00-0acf-11ea-8dba-f7416af84139.png)

**Comment by xaviripo** [comment]
The client hasn't responded in the original thread so we're marking this as closed.
