### ISSUE TITLE
Memory leak when utilizing the MathType and ChemType plugins in CKEditor 5

### ISSUE THREAD

**Issue by mabryl** [wiris/html-integrations#713]
## Description

1. Creating 10 instances of the CK5 Editor, he initial heap size in use by live JS objects is equal to 59 MB.
2. After destroying the instances of the CKEditor components, the final heap size in use by live JS objects is equal to 44 MB.

This behavior isn't occurring if we don't include the MathType plugin.

## Environment

@wiris/mathtype-ckeditor5": "^8.0.0

*What is the relevant software and their versions?*

- Editor - CKEditor 35.3.2
- Framework - Angular

## Steps to reproduce

1. Create 10 instances of CKE5 with the plugins included and observe the initial heap size in use by live JS objects - it should be 59 MB.
2. Destroy the CKE5 instances and the final heap size in use by live JS objects is equal to 44 MB

## Expected result

No memory leak should occur.

## Actual result

A memory leak occurs.

## Other details

This issue has been reported to the CKEditor team by one of our customers. I created this issue in your repo on their behalf 🙂

**Comment by icaparros-at-wiris** [comment]
Hello @mabryl,

I am trying to reproduce this issue:

I created 100 CKEditor instances with MathType and ChemType and I made a Snapshot. The memory usage of this snapshot is 272 MB. Then I destroyed all editors and I made a second Snapshot. This time, the memory usage is 216 MB. The difference between both Snapshots is 56MB.

![image](https://user-images.githubusercontent.com/91468181/212092077-3cfeea81-719d-4dd9-bf70-dfb42bdb5bcf.png)


I repeated the process, but this time I removed MathType and ChemType from all CKEditors. This time, the difference between both Snapshots is 53MB.

![image](https://user-images.githubusercontent.com/91468181/212093377-c26468da-50c4-4b5c-803d-d8eddc3fb0ca.png)

There is something that I am not checking correctly? Can you check the different memory that use on your browser, 10 CKEditors with MathType installed vs the 10 CKEditors destroyed?

**Comment by pablo-meyer** [comment]
Thanks @icaparros-at-wiris , didnt see this thread until now.  We reported this issue.  Any chance you can share the code that used?

**Comment by jguillen-at-wiris** [comment]
Hi @pablo-meyer, thanks for reaching us.

We are reviewing the sample code you sent via WeTransfer to our technical support case.
Shouldn't we find a trace there, we will provide further feedback and / or a sample code for you to check.

We will be back to you ASAP.

**Comment by jguillen-at-wiris** [comment]
This case was investigated via support ticket.

We released fixes to this issues in our last packages.
A few more fixes involving memory leaks will be released in our next package (hopefully next week).
Please, reopen if the new package release is not fixing your issue.

Thanks!
