### ISSUE TITLE
Will you replace the use of  the obsolete<mfenced> 

### ISSUE THREAD

**Issue by principleware** [wiris/html-integrations#781]
## Description

The <mfenced> element has been deprecated. Do you have a plan to replace its use?  Thanks.

## Environment

*Which version of MathType does this happen in?*

*What is the relevant software and their versions?*

- TinyMCE 6.0
- Angular

**Comment by jguillen-at-wiris** [comment]
Hi principleware.

Sorry for the late reply.
We believe you already realized <mfenced> was deprecated by mathml itself. Wiris is not planning to keep up the tag in a custome way.

Just in case you would be stuck still, the official documentation states the following:

"Note: Historically, the <mfenced> element was defined as a shorthand for writing fenced expressions and equivalent to an expanded form involving [<mrow>](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mrow) and [<mo>](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo) elements. Nowadays, it is recommended to use that equivalent form instead."

We confirm the use of <mrow> and <mo> works as expected, so you should be able to use these tags instead.
