### ISSUE TITLE
Could not upgrade @wiris/mathtype-ckeditor5 from v8.1.1 to v8.2.0

### ISSUE THREAD

**Issue by apfromiit** [wiris/html-integrations#792]
## Description

*What does the bug consist in?*

## Environment

*Which version of MathType does this happen in?*
^8.2.0

*What is the relevant software and their versions?*

CKEditor v36.0.1
MacOS

- *Editor (CKEditor, Froala, TinyMCE, etc.)*
- *Framework (Angular, React, etc.)*
- *Browser (Chrome, Firefox, etc.)*
- *Operating System (Windows, macOS, Ubuntu, etc.)*

## Steps to reproduce

*What are the steps needed to reproduce the bug?*
*Please be specific.*

To build CKEditor with latest version (v8.2.0) of @wiris/mathtype-ckeditor5

## Expected result

*What is the expected outcome of the steps above?*

Build should pass

## Actual result

*What is the actual outcome of the steps above?*

Build failed with below logs

ERROR in ./node_modules/@wiris/mathtype-ckeditor5/src/integration.js 6:0-78
Module not found: Error: Can't resolve '@wiris/mathtype-html-integration-devkit/src/telemeter' in '/Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-ckeditor5/src'
resolve '@wiris/mathtype-html-integration-devkit/src/telemeter' in '/Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-ckeditor5/src'
  Parsed request is a module
  using description file: /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-ckeditor5/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-ckeditor5/src/node_modules doesn't exist or is not a directory
      /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-ckeditor5/node_modules doesn't exist or is not a directory
      /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/node_modules doesn't exist or is not a directory
      /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/ap/Desktop/code.nosync/ckeditor5/node_modules
        existing directory /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit
          using description file: /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/package.json (relative path: .)
            using description file: /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/package.json (relative path: ./src/telemeter)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/src/telemeter doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/src/telemeter.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/src/telemeter.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/src/telemeter.wasm doesn't exist
              as directory
                /Users/ap/Desktop/code.nosync/ckeditor5/node_modules/@wiris/mathtype-html-integration-devkit/src/telemeter doesn't exist
      /Users/ap/Desktop/code.nosync/node_modules doesn't exist or is not a directory
      /Users/ap/Desktop/node_modules doesn't exist or is not a directory
      /Users/ap/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@wiris/mathtype-ckeditor5/src/plugin.js 25:0-49 101:24-44
 @ ./src/ckeditor.js 38:0-49 98:1-9

webpack 5.76.1 compiled with 1 error in 11836 ms

## Other details

*Is there anything else to consider?*

Build is successful with v8.1.1 without any such issue. While upgrading to v8.2.0, The build starts failing with above logs.

**Comment by apfromiit** [comment]
I found the latest version of @wiris/mathtype-ckeditor5 as 8.2.0 in https://www.npmjs.com/package/@wiris/mathtype-ckeditor5. Hence trying to upgrade in my code.

**Comment by icaparros-at-wiris** [comment]
Hello @apfromiit, 

Thank you for the information, we just released a new path version 8.2.2 with the fix.

**Comment by apfromiit** [comment]
npm ERR! 404  '@wiris/telemeter-wasm@^1.0.2' is not in this registry.
