### ISSUE TITLE
Uncaught runtime errors:

### ISSUE THREAD

**Issue by apfromiit** [wiris/html-integrations#816]
## Description

*What does the bug consist in?*

Uncaught runtime errors (Please refer error logs below)

## Environment

*Which version of MathType does this happen in? 8.3.1*

*What is the relevant software and their versions?*

- *Editor: CKEditor5 (38.0.1)*
- *Framework: Vue3 (3.2.47)*
- *Browser: Chrome*
- *Operating System: macOS*

## Steps to reproduce

I have integrated ckeditor with MathTypePlugin in my vue3 app. Was working without any issue so far.
Today I have upgraded my npm dependencies as below

    "@ckeditor/ckeditor5-alignment": "^38.0.1",
    "@ckeditor/ckeditor5-autoformat": "^38.0.1",
    "@ckeditor/ckeditor5-basic-styles": "^38.0.1",
    "@ckeditor/ckeditor5-block-quote": "^38.0.1",
    "@ckeditor/ckeditor5-dev-utils": "^37.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^38.0.1",
    "@ckeditor/ckeditor5-essentials": "^38.0.1",
    "@ckeditor/ckeditor5-font": "^38.0.1",
    "@ckeditor/ckeditor5-heading": "^38.0.1",
    "@ckeditor/ckeditor5-highlight": "^38.0.1",
    "@ckeditor/ckeditor5-horizontal-line": "^38.0.1",
    "@ckeditor/ckeditor5-image": "^38.0.1",
    "@ckeditor/ckeditor5-indent": "^38.0.1",
    "@ckeditor/ckeditor5-link": "^38.0.1",
    "@ckeditor/ckeditor5-list": "^38.0.1",
    "@ckeditor/ckeditor5-media-embed": "^38.0.1",
    "@ckeditor/ckeditor5-paragraph": "^38.0.1",
    "@ckeditor/ckeditor5-remove-format": "^38.0.1",
    "@ckeditor/ckeditor5-special-characters": "^38.0.1",
    "@ckeditor/ckeditor5-table": "^38.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^38.0.1",
    "@ckeditor/ckeditor5-typing": "^38.0.1",
    "@ckeditor/ckeditor5-upload": "^38.0.1",
    "@ckeditor/ckeditor5-vue": "^5.1.0",
    "@wiris/mathtype-ckeditor5": "^8.3.1",

Now I started receiving uncaught runtime errors whenever I open pages containing more than one ckeditor displayed.
The error is not happening on pages with single ckeditor displayed.
This issue does not occur if we visit a page with multiple ckeditor after visiting a page with single ckeditor.
This issue happens when we directly land on route containing multiple ckeditors. (I had three ckeditors on that page)

## Error logs:

telemeter_wasm.js:784 [Telemeter] Module ready (3 times)

closure invoked recursively or destroyed already
    at imports.wbg.__wbindgen_throw (webpack-internal:///./node_modules/@wiris/mathtype-html-integration-devkit/telemeter-wasm/telemeter_wasm.js:841:15)
    at http://localhost:8080/b92b3f8760238484.wasm:wasm-function[1073]:0x4726b
    at http://localhost:8080/b92b3f8760238484.wasm:wasm-function[920]:0x45fc8
    at __wbg_adapter_40 (webpack-internal:///./node_modules/@wiris/mathtype-html-integration-devkit/telemeter-wasm/telemeter_wasm.js:254:10)
    at real (webpack-internal:///./node_modules/@wiris/mathtype-html-integration-devkit/telemeter-wasm/telemeter_wasm.js:235:20)

## Expected result

Above runtime error should not occur

## Actual result

Uncaught runtime errors happening when opening a vue3 component containing more than one ckeditor.

**Comment by jguillen-at-wiris** [comment]
Good morning, @apfromiit !
Thanks for reporting this issue.
We have created a support case to review it.
We will be back to you as soon as we have some feedback!
Have a nice day!

**Comment by apfromiit** [comment]
Hi @icaparros-at-wiris,

Thanks for your response. But I don't use vite in my vue3 project. Please provide an alternate solution to use with vue.config.js.

**Comment by icaparros-at-wiris** [comment]
Hi @apfromiit,

Could you provide us a demo to reproduce the issue in your exact environment?

Thank you!

**Comment by apfromiit** [comment]
Demo repo to reproduce the issue: https://github.com/apfromiit/ck-error-demo

**Comment by apfromiit** [comment]
Upgraded our code to use ckeditor5 v39.0.0 and the issue is fixed. Thanks for the fix. Closing this issue.
