### ISSUE TITLE
click cancel or close  show error  Uncaught TypeError: Cannot read properties of null (reading 'getSelection')

### ISSUE THREAD

**Issue by wuxiaohan2023** [wiris/html-integrations#846]
## Description

when i click  rightTop close or bottom cancel button , console show error
<img width="1668" alt="image" src="https://github.com/wiris/html-integrations/assets/145582538/fb382d07-8719-4fd1-b060-6feeb20a197f">

## Environment

*Which version of MathType does this happen in?*
 "@wiris/mathtype-generic": "^8.5.0",

*What is the relevant software and their versions?*

- *Editor (CKEditor, Froala, TinyMCE, etc.)*
- *Framework (Angular, React, etc.)*
- *Browser (Chrome, Firefox, etc.)*
- *Operating System (Windows, macOS, Ubuntu, etc.)*

## Steps to reproduce

*What are the steps needed to reproduce the bug?*
*Please be specific.*

## Expected result

*What is the expected outcome of the steps above?*

## Actual result

*What is the actual outcome of the steps above?*

## Other details

mycode 
` <script src="node_modules/@wiris/mathtype-generic/wirisplugin-generic.js"></script>`

`  <div id="toolbar"></div>
    <div id="htmlEditor" contenteditable="true">Try me!</div>`

`    <script>
      const taget = document.getElementById("htmlEditor");
      const toolbar = document.getElementById("toolbar");
      var genericIntegrationProperties = {};
      genericIntegrationProperties.target = taget
      genericIntegrationProperties.toolbar = toolbar;

      var genericIntegrationInstance = new WirisPlugin.GenericIntegration(
        genericIntegrationProperties
      );
      genericIntegrationInstance.init();
      genericIntegrationInstance.listeners.fire("onTargetReady", {});

      WirisPlugin.currentInstance = this.wiris_generic;
      console.log(WirisPlugin.currentInstance)
     
    </script>
`

 when i `console.log( this.wiris_generic)`  show undefined

npmjs   https://www.npmjs.com/package/@wiris/mathtype-generic

I think it's the same as demo
<img width="966" alt="image" src="https://github.com/wiris/html-integrations/assets/145582538/a34c45a9-a0a8-406b-b3de-5b9a344a150b">

*Is there anything else to consider?*

**Comment by wu0211** [comment]
@carla-at-wiris  can you help

**Comment by carla-at-wiris** [comment]
Hi @wuxiaohan2023, thank you for your patience.

We are working on updating our documentation, as some steps are deprecated. The `wiris_generic` is actually an outdated variable that has not been removed from our documentation yet. It returns undefined since it does not exist anymore in our code. 

Now, the variable to use should be the Generic Integration Instance, and the code line where you use the `wiris_generic` should be as follows: 
```js
WirisPlugin.currentInstance = genericIntegrationInstance;
```

Please let us know if this fixes your issue. Thanks!

**Comment by wuxiaohan2023** [comment]
@carla-at-wiris   Thank you very much for your reply！

I am currently using this initialization method
<img width="861" alt="image" src="https://github.com/wiris/html-integrations/assets/145582538/40cb9a25-289e-4a6b-a8f8-0da5bf7bcede">


I have a question now, which is, we have already purchased credit vouchers from the agent and created a whitelist. So, what should I do with my online production environment？

**Comment by carla-at-wiris** [comment]
For what i can see in the code, the `wrs_int_init(target, toolbar)` method already fires the `onTargetReady` listener. So the last line does not seem necessary to me.

On the other hand, i would suggest you to contact us at [support@wiris.com](mailto:support@wiris.com) for license questions/issues.

Thanks!
