### ISSUE TITLE
Mathtype uses deprecated <mfenced> mathml for parenthesis and brackets

### ISSUE THREAD

**Issue by Sh4bbY** [wiris/html-integrations#864]
## Description

When using the MathType Toolbar-buttons for Parenthesis, Square brackets, Vertical bars or Curly brackets, it will render correctly within the MathType editor, but the generated MathML is using the [deprecated __\<mfenced\>__ element](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced).  so the parenthesis/brackets wont be visible in the browser when inserting the generated mathml.

There seem to be a workaround, when you use the Parenthesis from your keyboard, it won't be rendered correctly within the MathType editor, but the generated MathML is using <mo>(</mo> representation which will render corretly within the browser.

## Environment

@wiris/mathtype-ckeditor5@8.7.2
google-chrome 119.0.6045.160

## Steps to reproduce

- Visit [https://demo.wiris.com/mathtype/en/developers.php#mathml-latex_title](https://demo.wiris.com/mathtype/en/developers.php#mathml-latex_title)
- Enter a formula with a fraction wrapped in parenthesis.
- use the generated mathml in html and have a look at it in the browser.

![image](https://github.com/wiris/html-integrations/assets/2726032/bdca2c13-9dfd-4846-bec3-6c71bce56569)

## Expected result

```xml
<mrow><mo>(</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>)</mo></mrow>
```

## Actual result

```xml
<mfenced><mfrac><mn>1</mn><mn>2</mn></mfrac></mfenced>
```

*What is the actual outcome of the steps above?*

## Other details

https://github.com/wiris/html-integrations/issues/840 and https://github.com/wiris/html-integrations/issues/781 address similar issues but there is no solution to it yet.

**Comment by carla-at-wiris** [comment]
Hi @Sh4bbY, thanks for the report!

`mfenced` tag is deprecated inside web pages, i.e. when it's used as an HTML element. But **MathType Web** only uses MathML as an interchange format for mathematical equations, it's never inserted into the actual page, we insert rendered images.

We will let you know once the team in charge of manipulating the MathML starts working on removing the deprecated `mfenced` tag.

If you have more questions, please feel free to contact us again through GitHub or our official support email: [support@wiris.com](mailto:support@wiris.com)
