### ISSUE TITLE
Fraction Value Automatically Change

### ISSUE THREAD

**Issue by asadakkhan** [wiris/html-integrations#870]
## Description

When i enter 32/3 it automatically change to 3⅔

## Environment

Which version of MathType does this happen in?
Current Version   :  "@wiris/mathtype-ckeditor5": "^7.24.4",
What is the relevant software and their versions?

- Editor > CKEditor :  
"@ckeditor/ckeditor5-angular": "^2.0.1",
"@ckeditor/ckeditor5-build-classic": "^24.0.0",
- Framework > Angular : 11.2.14
- Browser > Chrome
- Operating System > Ubuntu

## Steps to reproduce

Enter the value of 32/3 in input box of ckeditor it will automatically change to 3⅔.

## Expected result

32/3 

## Actual result

3⅔.

## Other details

Is there anything else to consider?

**Comment by carla-at-wiris** [comment]
Hi @asadakkhan, thanks for reaching us.

Currently, we have the version `8.8.0` for the `@wiris/mathtype-ckeditor5` plugin. On this version, the bug you are mentioning is fixed. Please, upgrade your plugin version to see the changes and let us know if you have further issues. 🙂

You can also try the latest MathType version in this [online demo with MathType and CKEditor 5](https://demo.wiris.com/integrations/ckeditor/).
