### ISSUE TITLE
Getting issue while adding Math Type Plugin 

### ISSUE THREAD

**Issue by asadakkhan** [wiris/html-integrations#871]
## Description

*What does the bug consist in?*

Could not find a declaration file for module '@wiris/mathtype-ckeditor5/'. '/home/mustafaabdeali/Documents/ckexample/angularCk/node_modules/@wiris/mathtype-ckeditor5/src/plugin.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/wiris__mathtype-ckeditor5` if it exists or add a new declaration (.d.ts) file containing `declare module '@wiris/mathtype

Object literal may only specify known properties, and 'extraPlugins' does not exist in type '{ toolbar: { items: string[]; }; image: { toolbar: string[]; }; table: { contentToolbar: string[]; }; language: string; }'.ts(2353)
(property) extraPlugins: any[]

###Which version of MathType does this happen in?*
8.8.0
*What is the relevant software and their versions?*
Angular 16
Ckeditor 5

## Steps to reproduce

*What are the steps needed to reproduce the bug?*
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import MathType from '@wiris/mathtype-ckeditor5/';
ClassicEditor.builtinPlugins.push(MathType);

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet,CKEditorModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angularCk';
  public Editor = ClassicEditor.defaultConfig = {
    extraPlugins: [ MathType ],
    mathTypeParameters: {
       editor: 'ckeditor5',
       editorParameters: {}
    }
   };
}

##While Installing Type 

npm i --save-dev @types/wiris__mathtype-ckeditor5
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fwiris__mathtype-ckeditor5 - Not found
npm ERR! 404 
npm ERR! 404  '@types/wiris__mathtype-ckeditor5@*' is not in this registry.

**Comment by carla-at-wiris** [comment]
Hi @asadakkhan, thanks for taking the time to report this!

We were able to create a MathType integration with Angular@16 and Ckeditor@37, using the online [CKEditor5 builder](https://ckeditor.com/ckeditor-5/online-builder/) and following the [Angular + CKEditor instructions](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html).

We've attached a .zip file where you'll find the working example we created only by modifying a couple of things, all of them mentioned in the previous guides I've linked above.
[AngularCKEditor37MathType8.zip](https://github.com/wiris/html-integrations/files/13938109/AngularCKEditor37MathType8.zip)

Any further issues, please feel free to contact us through our email support [support@wiris.com](mailto:support@wiris.com), or by opening a new issue.
