### ISSUE TITLE
[CKEditor 5] options passed to `setData` are ignored

### ISSUE THREAD

**Issue by jonscheiding** [wiris/html-integrations#885]
## Description

CKEditor5 `setData` options are ignored

## Environment

*Which version of MathType does this happen in?*

`@wiris/mathtype-ckeditor5@8.7.2`

*What is the relevant software and their versions?*

- CKEditor 5
- Any Framework
- Any Browser
- Any OS

## Steps to reproduce

*What are the steps needed to reproduce the bug?*

* Initialize a CKE5 editor with with the MathType plugin added
* Call `editor.setData("<p>new content</p>", { batchType: { isUndoable: true } })`
* Notice that the change cannot be undone

## Expected result

The change should be undoable

## Actual result

The change is not undoable

## Other details

This is because the monkey-patched `data.set` method is not passing the options on to the inner `set` method.

**Comment by carla-at-wiris** [comment]
Hello @jonscheiding, thank you for reporting the issue and the suggested changes,

Our team took a look at it and will send your proposal to the next step. Once it's ready to release, we'll let you know! Any further issues, please feel free to contact us

**Comment by carla-at-wiris** [comment]
This has been included on our latest release. Check the following Pull Request for more information https://github.com/wiris/html-integrations/pull/958

Thank you for your contribution!
