### ISSUE TITLE
[CKEditor 5] import MathType >=8.8.1 leads to duplicated editors using CKEditor >=40.0.0 (version conflict)

### ISSUE THREAD

**Issue by guillome91** [wiris/html-integrations#932]
## Description

When you import the MathType plugin in the CKEditor  `import MathType from '@wiris/mathtype-ckeditor5/src/plugin.js';`  in my `app.js` then make `npm update`, it imports a `@ckeditor` node module inside the `node_modules/@wiris` one, leading to a [ckeditor-duplicated-modules](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules). 

## Environment

- CKEditor '>=40.0.0'.
- MathType '>= 8.8.1'.

Current version.

- CKEditor '41.2.1'.
-  MathType '8.8.3'
- Laravel '10.46' + PHP '8.1'.
-  NPM '9.2.0' + Vite.

## Steps to reproduce

Inside a laravel project, install the latest ckeditor **without** the online builder. 
(Following those steps [https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html#installing-necessary-dependencies](url) )
In `app.js` import the basic plugins to the ckeditor.

```
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
...
import MathType from '@wiris/mathtype-ckeditor5/src/plugin.js';
```
Run `npm update` or `npm install` then `npm run build`.
Open the project in browser.

## Expected result

The CKEditor is shown with the MathType button.

## Actual result

Broken CKEditor. The javascript console triggered a ckeditor-duplicated-modules error.

## Other details

After investigation this issue is due to the version required in  `@wiris/mathtype-ckeditor5/package.json` 
```
...
"depedencies":{
    "@ckeditor/ckeditor5-core": "^38.0.0",
    "@ckeditor/ckeditor5-engine": "^38.0.0",
    "@ckeditor/ckeditor5-ui": "^38.0.0",
    "@ckeditor/ckeditor5-widget": "^38.0.0",
    ... 
}
```
But the latest ckeditor version is `>=40.0.0`, so npm makes a local copy of the ckeditor module inside the wiris node module when you do `npm install` because of the version conflict. 
MathType `8.8.0` works with CKEditor `>=40.0.0` since the requirement is `>= 23.0.0`.

**Comment by carla-at-wiris** [comment]
Hello @guillome91, thank you for reporting this.

We've released a new version that removes the cap on the ckeditor5 versions the MathType uses. It's the `8.9.1`. Any further issues, please let us know!
