### ISSUE TITLE
Util.htmlSanitize strips style attribute from math tag

### ISSUE THREAD

**Issue by Roaann** [wiris/html-integrations#953]
## Description

When creating a formula with the MathType plugin within a CKEditor5 Classic Editor I can set a font for that formula. However when I try to set the data with a previously exported value it does not restore the style attribute of the math tag.

## Environment

CKEditor5 Classic Editor 41.3.1
"@wiris/mathtype-ckeditor5": "8.8.0" (because the latest mathtype version restricts CKEditor version to 38)

## Steps to reproduce
Go to the demo page of the [CKEditor MathType plugin](https://ckeditor.com/mathtype/#demo-mathtype)

Open the MathType plugin modal
 - Type a 'abc'
 - Change the font to Times New Roman
 - Accept the formula

Open up your console

Extract the data from the ckeditor by typing  `editors.classic.getData()`
 - which results in `<p><math style="font-family:'Times New Roman';" xmlns="http://www.w3.org/1998/Math/MathML"><mi>a</mi><mi>b</mi><mi>c</mi></math></p>`

Set the editor data by using `editors.classic.setData(<formula>)`
 - or for short use `editors.classic.setData(editors.classic.getData())`

## Expected result

The programatically inserted formula should keep the declared font

## Actual result

The previously inserted formula has now lost its declared font.

## Other details

A possible solution might be to add the style attribute to the ALLOWED_ATTR array in the htmlSanitize method of the Utils class in `@wiris/mathtype-html-integration-devkit/src/util.js` but I am uncertain if that is the right location to fix this issue.

**Comment by Roaann** [comment]
A somewhat unrelated question aswel: How do I set a default font family for the plugin modal through my CKEditor intialisation? In the documentation I can find how to [declare fonts](https://docs.wiris.com/mathtype/en/mathtype-integrations/mathtype-web-interface-features/custom-font-list.html), but I don't see how to set a default in the [CKEditor5 integration](https://docs.wiris.com/mathtype/en/mathtype-integrations/mathtype-for-html-editors/mathtype-for-ckeditor.html) section.

**Comment by carla-at-wiris** [comment]
Hello @Roaann, thank you for taking the time to report this!

We are currently preparing a new release and haven't had the time to look at your issue. We'll give you an answer shortly.

**Comment by carla-at-wiris** [comment]
Hello @Roaann,

Regarding the first reported issue, this is not reproducible on our latest version, `8.9.1`. We've made some improvements and the Font Family is not ignored anymore. This latest release also raises the restriction we had to use CKEditor `38`.

To set a fontFamily for all the generated formulas, the editorParameter `fontFamily` has to be defined when integrating MathType on CKEditor5. [Here's the documentation](https://docs.wiris.com/mathtype/en/mathtype-integrations/technical-configurations/parameters.html) about all the configurable parameters we offer. Here's an example on how the set the mentioned parameter when integrating MathType on CKEditor5:

```js
ClassicEditor
  .create(document.querySelector('#editor'), {
    plugins: [... Essentials, MathType ...],
    toolbar: [... 'MathType', 'ChemType' ...],
    // MathType configuration.
    // This will set the customizable MathType editor parameters, such as fontFamily, language, etc
    mathTypeParameters: {
      editorParameters: { fontFamily: 'Times New Roman' },
    },
  })
  .then((editor) => {
    ...
  })
  .catch((error) => {
    ...
  });
```

Any further issues, please feel free to contact us!
