### ISSUE TITLE
[CKEditor 5] Not able to insert new line after MathType equation in Firefox

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#96]
Original issue: https://github.com/ckeditor/ckeditor5/issues/8038

## 📝 Provide detailed reproduction steps (if any)

1. Add MathType equation as last element in the editor
2. Try to navigate to the end of the equation and press `enter`

### ✔️ Expected result

![0math2](https://user-images.githubusercontent.com/34380544/92367735-1948a100-f0f7-11ea-883a-3111515859a0.gif)

### ❌ Actual result

![0math3](https://user-images.githubusercontent.com/34380544/92367752-1ea5eb80-f0f7-11ea-9ecc-65012210defc.gif)

## 📃 Other details

* Browser: Firefox

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Me on Slack, replying to Xavier what to do to make FF put the selection outside that span (it apparently ends inside it):

> Hi Xavier! The model selection can be partially controlled via the schema, although we don’t have many rules implemented yet. Support for inline elements is only partial, so perhaps if the selection ends inside this element in the model, we could have a rule to move it out of such element. However, this won’t actually fix this issue as we’d need to hardcode whether we move the selection out to the left or to the right. At this stage we wouldn’t know in which direction it would need to be moved. That information is only available in the view layer.
> 
> So, the other thing is to have the view structure enforcing some things. You already use `contentedtiable=false` on the `<span>` that wraps an equation and that may be the only way of letting the browser know that it should not put the selection inside that element. Apparently, FF is a bit broken here. There might be some CSS that could help but it's a wild guess. I'd try with https://css-tricks.com/almanac/properties/u/user-select/.
> 
> So, we could try to do one more thing – write a custom mapping of a view -> model position so positions inside that span map to positions outside it.
> 
> A very similar kind of issue is resolved here: [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping)

**Comment by xaviripo** [comment]
This has been fixed in [@wiris/mathtype-ckeditor5@7.24.1](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5/v/7.24.1).
