### ISSUE TITLE
MathType Configurationjs depends on external (internet) access

### ISSUE THREAD

**Issue by even-steven** [wiris/html-integrations#978]
## Description

Our company is trying to use this library in a "closed" environment that has very strict network rules. They only allow network traffic from a limited number of domains. We noticed that the MathType library makes a POST to `https://www.wiris.net/demo/plugins/app/configurationjs` for configurations. In our closed environment, this call eventually times out and leaves the CKEditor unusable.

Is it possible to bundle this config file along with the plugin, or allow us to pass it in during plugin initialization? If not, what can you suggest, given our network situation?

Thanks!

## Expected result

Config resource is embedded with the plugin, or the ability to pass it during initialization.

## Actual result

MathType library makes a POST to `https://www.wiris.net/demo/plugins/app/configurationjs`

**Comment by xjiang-at-wiris** [comment]
Hi @even-steven 

Please contact our technical support team (support@wiris.com), so we can provide better service

**Comment by even-steven** [comment]
Thanks @xjiang-at-wiris, will do
